### ISSUE TITLE
Performance problem

### ISSUE THREAD

**Issue by tnthieu** [ateliee/jquery.schedule#17]
Hello,

When I have more than 100 timelines, it takes time to draw the bars. 
Could you provide paging options?

Thank you

**Comment by ateliee** [comment]
There are no paging options for this plugin.
If you want to respond, please implement the paging function yourself using the following method.

```
$("#schedule").timeSchedule('resetData');
$("#schedule").timeSchedule('addRow', timeline, data);
```

**Comment by tnthieu** [comment]
thank you
