### ISSUE TITLE
RowGroup

### ISSUE THREAD

**Issue by ripper04** [ateliee/jquery.schedule#18]
Hi Ateliee,
I have a issue:
I have a Deparment with employees A, B & C.
So, I want group Department for Row A, B & C like rowspan.
How can i display it?

For example:
```

                A      sc_bar
Department      B      sc_bar
                C      sc_bar

```
Thanks you for reading,
Have a nice day!

**Comment by ateliee** [comment]
Thank you for the question.

Added subtitle option in version 2.4.0.
See the demo ajax3 for details.

https://ateliee.github.io/jquery.schedule/demo/

**Comment by ripper04** [comment]
Hi Ateliee,
Thank you for your answer!

I saw and understood the demo ajax3.
Actually, If we have many (over 2 work time) sc_bar of only employee, the info or img, or name, ... duplicated in a row.
For example:
![image](https://user-images.githubusercontent.com/13957300/76217812-b0ff2c80-6245-11ea-89ee-bcdd3c51f566.png)

So, I think, Can we make a column for name or avatar or another info, and It's a key column for many sc_bar for this employee.
For example:
![image](https://user-images.githubusercontent.com/13957300/76218730-4fd85880-6247-11ea-92a2-fc3a5d6228ed.png)

**Comment by ateliee** [comment]
Currently it does not.

It may be possible to override and respond to CSS.

Thank you.
