### ISSUE TITLE
Some security findings

### ISSUE THREAD

**Issue by aileenscott-uleska** [ateliee/jquery.schedule#27]
Hi folks,

I hope you don’t mind, we were testing out our security automation tool and ran it against your project.  A few issues came out that you may want to check out - we weren’t sure how to submit a PDF here, so we uploaded it to https://source-security.co.uk/316f3833-929b-4a0b-9569-301c18298cfd/
Thanks.
Aileen

**Comment by ateliee** [comment]
Hello.

The notice of security is notified of in github and recognizes even this.
I coped than version 3.1.1.

Thank you for your indication.
