### ISSUE TITLE
Timeline indexes missmatch.

### ISSUE THREAD

**Issue by geoah** [ateliee/jquery.schedule#4]
Currently the `timelineData` array holds the timelines using the index that was provided in the initialization object.  

``` javascript
{
        rows : {
            '1': {},
            '2': {}
        }
}
```

But the `scheduleData` object references the timeline as an internal index. For example a schedule for the timeline in row with key 1 would be set as 0 in `scheduleData.timeline`. It would be useful and more safe to use the row's key instead of an index.

**Comment by daursdg** [comment]
Hello! I don't about js, but your schedule is good. I wanted to know, can you change your schedule functionality that it look liked [bbc tv schedule](http://www.bbc.co.uk/iplayer/guide)... That he shows NOW TIME (ON NOW)... Thank you, from Kazakhstan!
