### ISSUE TITLE
API Examples?

### ISSUE THREAD

**Issue by kferrio** [ateliee/jquery.schedule#7]
Thank you for this very useful and attractive control. 

I retrieve data from a RESTful API, and I would like to use that data to create and update the schedule.

Are there examples of dynamically setting the text and time values for `title` and `sc_Bar` using javascript?  

Again, thank you very much!

**Comment by HerHde** [comment]
I am also interested in an documentation of the API.
In my case, I want to fill the Schedule dynamically and update this data.

Greetings ;-)

**Comment by Kravs** [comment]
I'm also interested in updating data, I think It worth it to add docs

**Comment by junghee0217** [comment]
I'm a newbie in javascript and I've looking for documentations on how I can fill the table dynamically from the data of my database. Thanks for this awesome jQuery by the way. :)

**Comment by ateliee** [comment]
Added Ajax sample to demo page.
https://ateliee.github.io/jquery.schedule/demo/
